export enum ChartType {
  Line = "line",
  Area = "area",
  Bar = "bar",
  Pie = "pie",
  Donut = "donut",
  RadialBar = "radialBar",
  Scatter = "scatter",
  Bubble = "bubble",
  Heatmap = "heatmap",
  Candlestick = "candlestick",
  BoxPlot = "boxPlot",
  Radar = "radar",
  PolarArea = "polarArea",
  RangeBar = "rangeBar",
  RangeArea = "rangeArea",
  Treemap = "treemap",
}
