export enum ApplicationTypeCode {
  ACTTR = "ACTTR",
  CNTRT = "CNTRT",
  CPA = "CPA",
  CVA = "CVA",
  CVS = "CVS",
  DPR = "DPR",
  EWR = "EWR",
  INSP = "INSP",
  NA = "NA",
  NOV = "NOV",
  NPI = "NPI",
  OPA = "OPA",
  PHMSA = "PHMSA",
  RCL = "RCL",
  RDPP = "RDPP",
  STP = "STP",
  SWO = "SWO",
}
